---
- name: Deploy Docker Images
  hosts: all
  tasks:
    
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: ./docker-compose.yml
        dest: ./

    - name: Pull the Docker images specifed in docker-compose
      command: docker-compose pull

    # Detached mode is required, otherwise Jenkins build never exits
    # even though the docker-compose up has successfully executed
    - name: Run the pulled Docker images in detached mode
      command: docker-compose up -d