---
- name: Deploy Docker Images
  hosts: all
  vars_files:
  - ./backend/env-enc.yaml
  tasks:
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: ./docker-compose.yml
        dest: ./

    - name: Replace Jinja2 template with decrypted environment variables into env.yaml file
      template: 
        src: backend/env.j2
        dest: backend/env.yaml

    # Pull the Docker images from Docker Hub
    - name: Pull the Docker images specifed in docker-compose
      command: docker-compose pull

    # Detached mode is required, otherwise Jenkins build never exits
    # even though the docker-compose up command has successfully executed
    - name: Run the pulled Docker images in detached mode
      command: docker-compose up -d

    # This is added so that the Docker images of the previous builds
    # which will now become dangling images are removed
    - name: Prune the dangling Docker images
      command: docker image prune --force

    - name: Copy the env.yaml file to backend Docker container
      command: docker cp backend/env.yaml fintrack-backend:/usr/src/app/env.yaml